### ISSUE TITLE
1.0.0 Roadmap

### ISSUE THREAD

**Issue by hackergrrl** [noffle/friendpm#2]
- [x] Start the friendpm registry server on `install` or `publish` are run, if not already running (https://github.com/noffle/friendpm/issues/3)
- [x] Perform local network discovery of other friendpm users with [bonjour](https://github.com/watson/bonjour) (https://github.com/noffle/friendpm/issues/4)
- [ ] Add support for npm@5
- [ ] Design a friendpm graphic
- [ ] README prettification (elaborate on use cases)
- [ ] Share a write-up on reddit, HN, etc

**Comment by hackergrrl** [comment]
ah shoot it's good enough -- ship it! :rocket: :ship:
